services:
  - type: web
    name: fantasy-item-api
    runtime: python
    repo: https://github.com/YOUR_USERNAME/YOUR_REPO_NAME
    branch: main
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app:app --host 0.0.0.0 --port 10000
    envVars:
      - key: TRANSFORMERS_CACHE
        value: /opt/render/project/.cache/huggingface
    plan: free
